### ISSUE TITLE
Multiple textarea on same page

### ISSUE THREAD

**Issue by sagarjunnarkar** [derobins/wmd#14]
How to use wmd for multiple textarea on same page?

**Comment by BannedForLife** [comment]
Any update?

**Comment by rporrasluc** [comment]
Same problem here, much appreciated.

**Comment by steady-daddy** [comment]
Any update or monkey-patch for the same?

**Comment by derobins** [comment]
This code is no longer maintained. Use PageDown instead.

**Comment by steady-daddy** [comment]
Alright. Thank you.
